#config.yaml

data:
  train_data_path: "/home/vieira/datasets/SelfSupervisedLensless/prototype/train/"
  test_data_path: "/home/vieira/datasets/SelfSupervisedLensless/prototype/test/"
  save_path: "experiments/prototype/wiener_FFHQ_1/"
  data_format: "png"

model:
  model_type: "RecNet"
  deconv_layer: "WienerDeconv"
  encod_layer: "None"
  decoder_layer: "UNet270480"

deconv_layer:
  psf: "psf/prototype/radial_6per.npy"
  # {'w': 1.0, 'lambda_': 1e-4}
  w: 1.0
  lambda_: 0.0001

decoder_layer:
  none: "None"

encod_layer:
  none: "None"

training:
  batch_size: 32
  epochs: 200
  deconv_lr: "None"
  encoder_lr: "None"
  decoder_lr: 0.0001
  device: "cuda"
  resolution: 300
  num_workers: 4
  sampler_size: None