#config.yaml
# with output normalization (0,1)
data:
#  train_data_path: "/home/yagilab/Desktop/datasets/SelfSupervisedLensless/mini_FFHQ_256/train/"
#  test_data_path: "/home/yagilab/Desktop/datasets/SelfSupervisedLensless/mini_FFHQ_256/test/"
  train_data_path: "/home/vieira/datasets/SelfSupervisedLensless/simulation/train/"
  test_data_path: "/home/vieira/datasets/SelfSupervisedLensless/simulation/test/"
  save_path: "experiments/simulation/radial/leadmmu_FFHQ_1/"
  data_format: "npy"

model:
  model_type: "RecNet"
  deconv_layer: "UnrolledAdmmDeconv"
  encod_layer: "None"
  decoder_layer: "UNet270480"

deconv_layer:
  psf: "psf/simulation/256/radial_6per.npy"
  iters: 5
  hyper_parameter:
#    {'mu1': 0.6, 'mu2': 0.0008, 'mu3': 0.00001, 'tau': 1e-05}
    mu1: 0.6
    mu2: 0.0008
    mu3: 0.00001
    tau: 0.00001

decoder_layer:
  none: "None"

encod_layer:
  none: "None"

training:
  batch_size: 32
  epochs: 200
  deconv_lr: 0.0000
  encoder_lr: "None"
  decoder_lr: 0.0001
  device: "cuda"
  resolution: 256
  num_workers: 4
  sampler_size: None